export const GET_MOVIES = 'GET_MOVIES';
export const EDIT_TERM = 'EDIT_TERM';
export const ADD_NOMINATION = 'ADD_NOMINATION';
export const REMOVE_NOMINATION = 'REMOVE_NOMINATION';
export const CLEAR_NOMINATIONS = 'CLEAR_NOMINATIONS';
